### ISSUE TITLE
缺少一个css文件

### ISSUE THREAD

**Issue by huzyu** [Lemonreds/javaee-blog#2]
## 你好，在main.jsp会加载一个sign.css文件，实际上同级目录没有这个css文件

**Comment by Lemonreds** [comment]
可能是忘记删除了，不会影响运行的吧。

**Comment by huzyu** [comment]
### 嗯，不影响运行。再向您请教一个问题：在博客首页会展示所有的博客，请问这个div如何保证只显示一部分的内容？我看显示的源码\<span>${article.content}</span>\，为什么这个span没有把content的内容全部加载呢？抱歉我的前端功力太渣了，请大神赐教
![blog.png](https://i.loli.net/2018/03/22/5ab3b3cf1129d.png)

**Comment by Lemonreds** [comment]
@huzyu 不好意思 现在才看到，是在转发之前就对 content 进行了裁剪，可以参考这个 ``ArticleService``这个类

**Comment by huzyu** [comment]
### 谢谢你的回答，我感觉现在有思路实现这个效果了，谢啦
